name: scorecard

on:
  schedule:
    - cron: '37 4 * * 2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@v2.4.2
        with:
          publish_results: false
